const site_name = 'Navigation Page Application';
const article_text = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus lectus ac orci pulvinar ornare. Etiam vestibulum laoreet rhoncus. Donec id ligula non mauris condimentum tincidunt. In condimentum nibh tellus, at facilisis orci mattis at. Sed nisi nunc, blandit a sem vel, varius pellentesque dui. Vestibulum malesuada, dolor eu eleifend tristique, arcu orci efficitur sem, et auctor quam nibh nec urna. Sed molestie ultrices finibus. Donec vel tempor mi. Proin sed ipsum quis ligula viverra mollis. Etiam porttitor maximus hendrerit. Curabitur vitae elit nec magna auctor commodo. Sed vitae erat sem. Aliquam luctus dapibus massa eget sodales. Pellentesque eu accumsan diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam ipsum tellus, aliquam ac ultricies nec, finibus eu metus.

Nullam vitae vestibulum magna, nec commodo libero. Nulla ut felis enim. Phasellus non nulla sit amet magna aliquam venenatis eget eu sapien. In hac habitasse platea dictumst. Ut magna augue, tincidunt eu nulla eget, tristique aliquam enim. Ut quis maximus mauris. Sed facilisis justo non neque consectetur, nec accumsan nisl tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum eleifend suscipit dolor vitae luctus. Proin dignissim scelerisque diam et rhoncus. Proin tincidunt velit nulla, in hendrerit enim placerat eget. Phasellus iaculis quam non molestie ullamcorper. Aliquam ullamcorper sapien sit amet nunc bibendum ultrices. Pellentesque varius arcu ac lectus iaculis pellentesque. Nulla sed semper sem. Cras hendrerit velit leo, et sagittis leo commodo non.

Nulla facilisi. Donec ac imperdiet est. Aliquam suscipit rutrum feugiat. Aenean quis tristique elit. Nullam interdum sem sit amet erat scelerisque convallis. Morbi scelerisque cursus neque at sagittis. Proin pharetra tempor erat nec eleifend. Ut vestibulum, arcu nec venenatis commodo, metus massa vestibulum diam, vel blandit nunc ante in mi. Mauris sagittis bibendum sapien, et maximus turpis lobortis placerat.

Donec volutpat mollis metus, in fringilla leo. Ut imperdiet porttitor molestie. Nunc vel rhoncus lacus. Phasellus in nibh ultrices, efficitur lacus sit amet, pharetra mauris. Suspendisse massa erat, consectetur varius scelerisque ut, aliquam a nisl. Sed cursus sit amet arcu vel rhoncus. Nam auctor leo sit amet mattis cursus. Donec suscipit velit sit amet scelerisque pretium. Etiam fringilla velit a dolor accumsan efficitur. Pellentesque in efficitur orci.

Suspendisse non sem mattis, ultricies nulla ut, imperdiet arcu. Donec eros lacus, varius non nisi sit amet, luctus posuere odio. Pellentesque vitae egestas sapien. Pellentesque diam arcu, sodales vel augue ut, euismod volutpat dui. Curabitur efficitur hendrerit hendrerit. Nam fringilla pellentesque quam ac lacinia. Praesent ut lorem nec dui mattis vehicula a vel ipsum. Donec laoreet sapien at velit lobortis, a porttitor ligula venenatis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis orci odio, rhoncus et mi at, convallis tempus tortor. Nulla eleifend quis eros vitae pretium.`;

export {site_name, article_text}